### ISSUE TITLE
Having an issue with the socket io loading while testing the game

### ISSUE THREAD

**Issue by computersandstuff** [dperelman/clues-for-two#53]
Specs for reproducing bug:
NPM + Nodejs on Windows 10
Latest Firefox or Google Chrome Browser (Didn't work on either)
Installed by extracting zip, cd'ing to root directory (clues-for-two), `npm install`, `npm start` both in same root directory, opening a browser to port 2000.

The following error is in the console:
`Uncaught SyntaxError: expected expression, got '.'`

This is because the js that is being referenced (js/socket.io.js) simply has this `../../external/socket.io.js` and the browser doesn't understand it.

Ultimately the main .js file produces this error: `Uncaught ReferenceError: io is not defined
    <anonymous> http://127.0.0.1:2000/js/clues-for-two.js:1
`

Apparently it cannot reach the socket.io.js script and cannot continue in anything else including starting a game. However if I replace the `public/js/socket.io.js` with the `external/socket.io.js` it will work just fine. Apparently the browser cannot access the file because it is outside of the public directory. Is there something I did wrong while installing?

**Comment by dperelman** [comment]
The issue is the the file in `public/js` is a symlink and Windows doesn't support symlinks. Your workaround of just copying that file is probably the appropriate fix. Note the [google-fonts](https://github.com/dperelman/clues-for-two/blob/master/public/css/google-fonts) directory is also a symlink, so you'll want to copy that directory, too.

(Those are symlinks because as a personal style I like to keep any code I'm pulling in from elsewhere in a separate `external/` directory to make it clear which code is part of the repo as opposed to really being part of another project.)

The git for Windows documentation has [a page on symlinks](https://github.com/git-for-windows/git/wiki/Symbolic-Links) and there's [this StackOverflow thread](https://stackoverflow.com/questions/5917249/git-symlinks-in-windows) on another way to handle it, which is basically scripting the copy. Both approaches are probably overkill for this; just manually copy the files. Or use Linux/WSL.

**Comment by computersandstuff** [comment]
Thanks! I booted up ubuntu and loaded it on there and it seems to work now without moving the socket.io.js to the public folder
